name: compilation test on push in main

on:
  push:
    branches:
      - main

jobs:
  compilation_test:
    name: compilation test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install packages
        run: sudo apt-get install build-essential python3 default-jdk -y
      - name: run tests
        run: sh tests/test.sh
